### ISSUE TITLE
Post to source_object_map returns 500 error

### ISSUE THREAD

**Issue by lrrfantasy** [unicef/rhizome#27]
@Adusei 

When trying to map an indicator to another, console returns error 
`POST http://localhost:8000/api/v1/source_object_map/?format=json 500 (INTERNAL SERVER ERROR)`

**Comment by Adusei** [comment]
fixed with 
https://github.com/unicef/rhizome/commit/22229eadd406a4edccfa3c739238285809fd1863
and
https://github.com/unicef/rhizome/commit/83b3084946bb0bb76be30ce79d3691e6ac79f1dd
