### ISSUE TITLE
Tool Tips not Working

### ISSUE THREAD

**Issue by Adusei** [unicef/rhizome#3]
Comparing rhizome.work to polio.seedscientific i notice that some ( but not all ) tool tips are not working.  

Places where this needs to be fixed:

   - Nigeria Campaign Monitoring - http://rhizome.work/datapoints/nga-campaign-monitoring/Nigeria/2015/06/
   - All Maps ( when hovering on a sub -region the location name should show up
   - District Dashboard http://rhizome.work/datapoints/district-dashboard/Afghanistan/2014/11/

**Comment by zhangsichu** [comment]
fixed at the commit 3f586d07577bd4807854dbcd41be7d09bd90eaac

**Comment by Adusei** [comment]
:):):):):):)
