### ISSUE TITLE
Gulp dev does not watch for changes on screen.scss

### ISSUE THREAD

**Issue by Adusei** [unicef/rhizome#8]

**Comment by morlay** [comment]
https://github.com/unicef/rhizome/blob/master/webapp/tasks/config/sass.js#L13
the config `src` is for watching, need to contains the `screen.scss`

or change here.
https://github.com/unicef/rhizome/blob/master/webapp/tasks/sass.js#L22
let `entry` and `src` be both included.

**Comment by zhangsichu** [comment]
this issue is fixed by the commit cb01d29541dda986f5c2ded49c8a71db97abc306 , the src path need include the style files to be watched.
